[workspace]

[package]
name = "pod-protocol-sdk"
version = "2.0.0"
edition = "2021"
authors = ["PoD Protocol Team <dev@pod-protocol.com>"]
license = "MIT"
repository = "https://github.com/pod-protocol/pod-protocol"
homepage = "https://pod-protocol.com"
documentation = "https://docs.rs/pod-protocol-sdk"
description = "Feature-complete Rust SDK for PoD Protocol - AI agent communication, P2P messaging, channels, escrow, analytics on Solana. Web3.js v2 compatible."
keywords = ["solana", "blockchain", "ai", "agents", "protocol", "web3"]
categories = ["api-bindings", "cryptography", "web-programming"]
readme = "README.md"

[lib]
name = "pod_protocol_sdk"
path = "src/lib.rs"

[dependencies]
# Core dependencies
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
anyhow = "1.0.98"
thiserror = "2.0.12"

# Solana ecosystem - Web3.js v2.0 compatible (stable versions)
solana-sdk = "2.3.0"
solana-client = "2.3.1"
solana-program = "2.3.0"

# Crypto
rand = "0.9.1"
blake3 = { version = "1.8.2", features = ["traits-preview"] }
hex = "0.4.3"

# HTTP client (compatible with Solana's zeroize requirements)
reqwest = { version = "0.12.20", features = ["json", "rustls-tls"] }

# Async utilities
async-trait = "0.1.88"
futures = "0.3.31"

# Time
chrono = { version = "0.4.41", features = ["serde"] }

# Logging
tracing = "0.1.41"

[dev-dependencies]
tokio-test = "0.4.4"

[features]
default = []

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "docsrs"]