# Agent Configuration: .qodo/agents/pod-protocol/agent.toml

# 1. Core Settings
version         = "1.0"
model           = "claude-4-sonnet"
mcp_file        = "./mcp.json"

# 2. Global Behavior
[behavior]
max_tokens      = 4096
temperature     = 0.1

# 3. Available Tools
available_tools = ["context7", "task-manager"]

# 4. Command Definitions

# 4.1 Research Mode: exploration and discovery
[commands.research]
description     = "Research external context and dependencies for PoD-Protocol"
instructions    = '''
You are in Research Mode:
- Search GitHub issues, RFCs, or external docs via context7.
- Summarize best practices for similar Solana protocols.
- Report relevant APIs, security guidelines, and performance benchmarks.
'''
execution_strategy = "plan"

# 4.2 Docs Gathering Mode: fetch inline docs
[commands.gather-docs]
description     = "Fetch and inject relevant project documentation"
instructions    = '''
You are in Docs Gathering Mode:
- Use context7 MCP to retrieve module-level and API docs.
- Collate code comments from programs/pod-com/, sdk/, and cli/.
- Produce a structured summary per directory.
'''
execution_strategy = "plan"

# 4.3 Planning Mode: design PRs and strategy
[commands.plan]
description     = "Generate development plan and PR outlines"
instructions    = '''
You are in Planning Mode:
- Analyze current repo state via fs/git tools.
- Propose high-level feature breakdown into PRs.
- For each PR: suggest branch name, commit message, and title.
'''
execution_strategy = "plan"

# 4.4 Execution Mode: code generation and refactoring
[commands.execute]
description     = "Generate or refactor code based on a prompt"
instructions    = '''
You are in Execution Mode:
- Work on the target file or module.
- Provide diffs or full-file code with syntax highlighting.
- Adhere to TS strict mode, Tailwind + shadcn/ui, and Anchor v0.27.
'''
execution_strategy = "immediate"

[commands.execute.arguments]
file            = { type = "string", required = false, description = "Target file or directory" }

# 4.5 Test Mode: scaffold tests and validations
[commands.test]
description     = "Create or update unit and integration tests"
instructions    = '''
You are in Test Mode:
- Generate Rust tests under programs/pod-com/tests or JS tests under tests/.
- Use Jest/Testing Library for frontend, and Anchor testing for contracts.
- Include inline comments explaining assertions and mocks.
'''
execution_strategy = "immediate"

[commands.test.arguments]
file            = { type = "string", required = false, description = "Test file or directory" }

# 5. Default Pod-Protocol Command Alias
[commands.pod-protocol]
description     = "Alias to select mode or run default Execution Mode"
instructions    = '''
If you specify a mode (research, gather-docs, plan, execute, test), route to that command.
Otherwise, enter Execution Mode.
'''
arguments = { mode = { type = "string", required = false, description = "Mode: research|gather-docs|plan|execute|test" }, file = { type = "string", required = false, description = "Target file or directory" } }