# Bun configuration for PoD Protocol
# Ensures compatibility with Solana/Anchor ecosystem

[install]
# Use hardlinks for faster installs
hardlinks = true

# Exact versions for better compatibility
exact = true

# Auto-install peer dependencies
auto = true

# Registry configuration
registry = "https://registry.npmjs.org"

# Cache configuration
cache.dir = "~/.bun/install/cache"

[test]
# Test configuration
timeout = 10000

[run]
# Environment variables for Solana compatibility
env.NODE_OPTIONS = "--max-old-space-size=8192"
env.ANCHOR_PROVIDER_URL = "https://api.devnet.solana.com"
env.ANCHOR_WALLET = "~/.config/solana/id.json"

# Prefer Bun runtime for scripts
prefer-offline = true

[dev]
# Development server configuration
hot = true
watch = true
