# Docker Compose Override for Development
# This file is automatically loaded alongside docker-compose.yml
# Use this for development-specific configurations

version: '3.8'

services:
  # Phala Cloud App - Development overrides
  app:
    environment:
      NODE_ENV: development
    volumes:
      # Mount local app code if developing locally
      # - ./packages/frontend/frontend:/app:delegated

  # API Server - Development overrides
  api-server:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      # Mount source code for hot reloading in development
      - ./packages/api-server/api-server/src:/app/src:ro
      - ./packages/api-server/api-server/prisma:/app/prisma:ro
    command: ["npm", "run", "dev"]

  # MCP Server - Development overrides  
  mcp-server:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      MCP_MODE: development
      ENABLE_ANALYTICS: true
    volumes:
      # Mount source code for hot reloading in development
      - ./packages/mcp-server/src:/app/src:ro
      - ./packages/mcp-server/config:/app/config:ro
    command: ["npm", "run", "dev"]

  # PostgreSQL - Development overrides
  postgres:
    environment:
      POSTGRES_PASSWORD: dev_password
    ports:
      # Expose database port in development
      - "5432:5432"

  # Redis - Development overrides
  redis:
    command: redis-server --appendonly yes --requirepass dev_redis_password
    ports:
      # Expose Redis port in development
      - "6379:6379"