[package]
name = "basic-agent-example"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "basic-agent"
path = "src/main.rs"

[dependencies]
pod-sdk-core = { path = "../../crates/pod-sdk-core" }
tokio = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }

# Solana
solana-sdk = { workspace = true } 