[package]
name = "pod-sdk-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Shared type definitions for the PoD Protocol Rust SDK"
keywords.workspace = true
categories.workspace = true

[lib]
name = "pod_sdk_types"
path = "src/lib.rs"

[dependencies]
# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
borsh = { workspace = true }
borsh-derive = { workspace = true }

# Solana
solana-sdk = { workspace = true }
solana-program = { workspace = true }

# Time
chrono = { workspace = true }

# Utilities
derive_more = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[features]
default = [] 