name: CI
on: [push, pull_request]

jobs:
  lint:
    name: "🎨 Lint & Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana CLI
        run: |
          echo "⚙️ Installing Solana CLI..."
          set -e
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.26/install)" || {
            echo "❌ Failed to install Solana CLI"
            exit 1
          }
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version || {
            echo "❌ Failed to verify Solana CLI installation"
            exit 1
          }
          echo "✅ Solana CLI installed and verified successfully"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
            sdk/node_modules
            cli/node_modules
            frontend/node_modules
          key: ${{ runner.os }}-lint-${{ hashFiles('**/bun.lock', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint-

      - name: Install dependencies
        run: |
          echo "📦 Installing workspace dependencies for linting..."
          set -e
          
          echo "🔧 Installing root dependencies..."
          bun install --frozen-lockfile || {
            echo "❌ Failed to install root dependencies"
            exit 1
          }
          echo "✅ Root dependencies installed successfully"
          
          echo "🔧 Installing SDK dependencies..."
          cd sdk
          bun install --frozen-lockfile || {
            echo "❌ Failed to install SDK dependencies"
            exit 1
          }
          echo "✅ SDK dependencies installed successfully"
          
          echo "🔧 Installing CLI dependencies..."
          cd ../cli
          bun install --frozen-lockfile || {
            echo "❌ Failed to install CLI dependencies"
            exit 1
          }
          echo "✅ CLI dependencies installed successfully"
          
          echo "🔧 Installing frontend dependencies..."
          cd ../frontend
          bun install --frozen-lockfile || {
            echo "❌ Failed to install frontend dependencies"
            exit 1
          }
          echo "✅ Frontend dependencies installed successfully"
          echo "🎉 All dependencies installed successfully"

      - name: Lint TypeScript & Prettier
        run: |
          echo "🎨 Running TypeScript and Prettier linting..."
          set -e
          bun run lint:all || {
            echo "❌ TypeScript and Prettier linting failed"
            exit 1
          }
          echo "✅ TypeScript and Prettier linting passed"

      - name: Lint Frontend
        run: |
          echo "🎨 Running frontend linting..."
          set -e
          cd frontend
          bun run lint || {
            echo "❌ Frontend linting failed"
            exit 1
          }
          echo "✅ Frontend linting passed"

      - name: Lint Rust
        run: |
          echo "🦀 Running Rust linting..."
          set -e
          cd programs/pod-com
          
          echo "🔧 Checking Rust formatting..."
          cargo fmt -- --check || {
            echo "❌ Rust formatting check failed"
            exit 1
          }
          echo "✅ Rust formatting check passed"
          
          echo "🔧 Running Rust clippy..."
          cargo clippy -- -D warnings || {
            echo "❌ Rust clippy check failed"
            exit 1
          }
          echo "✅ Rust clippy check passed"

  security-audit:
    name: "🔒 Security Audit (LOW-01)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: |
          echo "🔒 Installing cargo-audit..."
          set -e
          cargo install cargo-audit --locked || {
            echo "❌ Failed to install cargo-audit"
            exit 1
          }
          echo "✅ cargo-audit installed successfully"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
            sdk/node_modules
            cli/node_modules
            frontend/node_modules
          key: ${{ runner.os }}-security-${{ hashFiles('**/bun.lock', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-security-

      - name: Install dependencies
        run: |
          echo "📦 Installing workspace dependencies for security audit..."
          set -e
          
          echo "🔧 Installing root dependencies..."
          bun install --frozen-lockfile || {
            echo "❌ Failed to install root dependencies"
            exit 1
          }
          echo "✅ Root dependencies installed successfully"
          
          echo "🔧 Installing SDK dependencies..."
          cd sdk
          bun install --frozen-lockfile || {
            echo "❌ Failed to install SDK dependencies"
            exit 1
          }
          echo "✅ SDK dependencies installed successfully"
          
          echo "🔧 Installing CLI dependencies..."
          cd ../cli
          bun install --frozen-lockfile || {
            echo "❌ Failed to install CLI dependencies"
            exit 1
          }
          echo "✅ CLI dependencies installed successfully"
          
          echo "🔧 Installing frontend dependencies..."
          cd ../frontend
          bun install --frozen-lockfile || {
            echo "❌ Failed to install frontend dependencies"
            exit 1
          }
          echo "✅ Frontend dependencies installed successfully"
          echo "🎉 All dependencies installed successfully"

      - name: Rust Security Audit
        run: |
          echo "🔒 Running Rust security audit..."
          set -e
          cd programs/pod-com
          cargo audit --deny warnings || {
            echo "❌ Rust security audit failed"
            exit 1
          }
          echo "✅ Rust security audit passed"

      - name: Node.js Security Audit (Root)
        run: |
          echo "🔒 Running Node.js security audit for root workspace..."
          set -e
          bun audit --audit-level high || {
            echo "❌ Root workspace security audit failed"
            exit 1
          }
          echo "✅ Root workspace security audit passed"

      - name: Node.js Security Audit (SDK)
        run: |
          echo "🔒 Running Node.js security audit for SDK..."
          set -e
          cd sdk
          bun audit --audit-level high || {
            echo "❌ SDK security audit failed"
            exit 1
          }
          echo "✅ SDK security audit passed"

      - name: Node.js Security Audit (CLI)
        run: |
          echo "🔒 Running Node.js security audit for CLI..."
          set -e
          cd cli
          bun audit --audit-level high || {
            echo "❌ CLI security audit failed"
            exit 1
          }
          echo "✅ CLI security audit passed"

      - name: Node.js Security Audit (Frontend)
        run: |
          echo "🔒 Running Node.js security audit for Frontend..."
          set -e
          cd frontend
          bun audit --audit-level high || {
            echo "❌ Frontend security audit failed"
            exit 1
          }
          echo "✅ Frontend security audit passed"

      - name: npm Security Audit
        run: |
          echo "🔒 Running npm audit for all workspaces..."
          set -e
          for dir in . sdk cli frontend; do
            if [ -f "$dir/package.json" ]; then
              echo "📦 Auditing $dir..."
              cd $dir
              npm install --package-lock-only --ignore-scripts || {
                echo "❌ Failed to create package-lock.json for $dir"
                exit 1
              }
              npm audit --audit-level=high || {
                echo "❌ npm security audit failed for $dir"
                exit 1
              }
              echo "✅ npm security audit passed for $dir"
              cd ..
            fi
          done
          echo "🎉 All npm security audits completed successfully"

      - name: Check for known vulnerabilities in dependencies
        run: |
          echo "🔍 Checking for vulnerable patterns in code..."
          # Check for common security anti-patterns
          if grep -r --include="*.ts" --include="*.js" --include="*.rs" -n "eval\|innerHTML\|dangerouslySetInnerHTML" . ; then
            echo "⚠️ Warning: Found potentially dangerous patterns. Review for security implications."
          fi
          
          # Check for hardcoded secrets (basic patterns)
          if grep -r --include="*.ts" --include="*.js" --include="*.rs" -i "password\|secret\|key\|token" . | grep -v "test\|example\|placeholder" | grep "=" ; then
            echo "⚠️ Warning: Found potential hardcoded credentials. Review for security implications."
          fi
          
          echo "✅ Security pattern check completed"

  build:
    name: "🏗️ Build All"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          echo "📦 Installing system dependencies for build..."
          set -e
          sudo apt-get update || {
            echo "❌ Failed to update package lists"
            exit 1
          }
          sudo apt-get install -y pkg-config build-essential libudev-dev || {
            echo "❌ Failed to install system dependencies"
            exit 1
          }
          echo "✅ System dependencies installed successfully"

      - name: Install Anchor CLI via avm
        run: |
          echo "⚙️ Installing Anchor CLI for build..."
          set -e
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force || {
            echo "❌ Failed to install AVM"
            exit 1
          }
          avm install 0.31.1 || {
            echo "❌ Failed to install Anchor version 0.31.1"
            exit 1
          }
          avm use 0.31.1 || {
            echo "❌ Failed to use Anchor version 0.31.1"
            exit 1
          }
          echo "✅ Anchor CLI installed and configured successfully"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.cargo/registry
            ~/.cargo/git
            target
            node_modules
            sdk/node_modules
            cli/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/bun.lock', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          echo "📦 Installing workspace dependencies for build..."
          set -e
          
          echo "🔧 Installing root dependencies..."
          bun install --frozen-lockfile || {
            echo "❌ Failed to install root dependencies"
            exit 1
          }
          echo "✅ Root dependencies installed successfully"
          
          echo "🔧 Installing frontend dependencies..."
          cd frontend
          bun install --frozen-lockfile || {
            echo "❌ Failed to install frontend dependencies"
            exit 1
          }
          echo "✅ Frontend dependencies installed successfully"
          echo "🎉 All dependencies installed successfully"

      - name: Build Solana Program
        run: |
          echo "⚓ Building Anchor program..."
          set -e
          anchor build || {
            echo "❌ Failed to build Anchor program"
            exit 1
          }
          echo "✅ Anchor program built successfully"

      - name: Build SDK
        run: |
          echo "📦 Building SDK..."
          set -e
          cd sdk
          bun run build || {
            echo "❌ Failed to build SDK"
            exit 1
          }
          echo "✅ SDK built successfully"

      - name: Build CLI
        run: |
          echo "🔧 Building CLI..."
          set -e
          cd cli
          bun run build || {
            echo "❌ Failed to build CLI"
            exit 1
          }
          echo "✅ CLI built successfully"

      - name: Build Frontend
        run: |
          echo "🌐 Building Frontend..."
          set -e
          cd frontend
          bun install --frozen-lockfile || {
            echo "❌ Failed to install frontend dependencies"
            exit 1
          }
          bun run build || {
            echo "❌ Failed to build frontend"
            exit 1
          }
          echo "✅ Frontend built successfully"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/deploy/
            target/idl/
            sdk/dist/
            cli/dist/
            frontend/.next/

  test:
    name: "🧪 Test Suite"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          echo "📦 Installing system dependencies for testing..."
          set -e
          sudo apt-get update || {
            echo "❌ Failed to update package lists"
            exit 1
          }
          sudo apt-get install -y pkg-config build-essential libudev-dev netcat-openbsd curl || {
            echo "❌ Failed to install system dependencies"
            exit 1
          }
          echo "✅ System dependencies installed successfully"

      - name: Install Anchor CLI via avm
        run: |
          echo "⚙️ Installing Anchor CLI for testing..."
          set -e
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force || {
            echo "❌ Failed to install AVM"
            exit 1
          }
          avm install 0.31.1 || {
            echo "❌ Failed to install Anchor version 0.31.1"
            exit 1
          }
          avm use 0.31.1 || {
            echo "❌ Failed to use Anchor version 0.31.1"
            exit 1
          }
          echo "✅ Anchor CLI installed and configured successfully"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
            sdk/node_modules
            cli/node_modules
          key: ${{ runner.os }}-test-${{ hashFiles('**/bun.lock', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-

      - name: Install dependencies
        run: |
          echo "📦 Installing workspace dependencies for testing..."
          set -e
          
          echo "🔧 Installing root dependencies..."
          bun install --frozen-lockfile || {
            echo "❌ Failed to install root dependencies"
            exit 1
          }
          echo "✅ Root dependencies installed successfully"
          
          echo "🔧 Installing frontend dependencies..."
          cd frontend
          bun install --frozen-lockfile || {
            echo "❌ Failed to install frontend dependencies"
            exit 1
          }
          echo "✅ Frontend dependencies installed successfully"
          echo "🎉 All dependencies installed successfully"

      - name: Setup Solana keypair
        run: |
          echo "🔑 Setting up Solana keypair..."
          set -e
          mkdir -p ~/.config/solana || {
            echo "❌ Failed to create Solana config directory"
            exit 1
          }
          solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json || {
            echo "❌ Failed to generate Solana keypair"
            exit 1
          }
          solana config set --url localhost || {
            echo "❌ Failed to configure Solana URL"
            exit 1
          }
          echo "✅ Solana keypair and configuration setup successfully"

      - name: Start and Wait for Solana Test Validator
        run: |
          echo "🚀 Starting Solana test validator..."
          solana-test-validator --reset --quiet --log /tmp/validator.log &
          VALIDATOR_PID=$!
          echo "Validator PID: $VALIDATOR_PID"
          
          echo "⏳ Waiting for validator to be ready..."
          for i in {1..60}; do
            if nc -z localhost 8899 && nc -z localhost 8900; then
              echo "✅ Validator is ready on ports 8899 (RPC) and 8900 (WebSocket)"
              
              # Additional health check
              if curl -s -X POST -H "Content-Type: application/json" \
                -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}' \
                http://localhost:8899 | grep -q '"result":"ok"'; then
                echo "✅ Validator health check passed"
                break
              fi
            fi
            
            if [ $i -eq 60 ]; then
              echo "❌ Validator did not start within 60 seconds"
              echo "📋 Validator logs:"
              if [ -f /tmp/validator.log ]; then
                tail -50 /tmp/validator.log
              fi
              kill $VALIDATOR_PID 2>/dev/null || true
              exit 1
            fi
            
            if [ $((i % 10)) -eq 0 ]; then
              echo "⏳ Attempt $i/60: Still waiting for validator..."
            fi
            sleep 1
          done

      - name: Run Anchor Tests
        run: |
          echo "🧪 Running Anchor tests..."
          set -e
          anchor test --skip-build || {
            echo "❌ Anchor tests failed"
            exit 1
          }
          echo "✅ Anchor tests passed"

      - name: Run SDK & CLI Tests
        run: |
          echo "🧪 Running SDK & CLI tests..."
          set -e
          bun run test || {
            echo "❌ SDK & CLI tests failed"
            exit 1
          }
          echo "✅ SDK & CLI tests passed"

      - name: Run Compute Unit Benchmarks
        run: |
          echo "⚡ Running compute unit benchmarks..."
          set -e
          if [ -f tests/performance-benchmark.test.ts ]; then
            echo "📊 Found performance benchmark, running..."
            cd tests
            bun run performance-benchmark.test.ts || {
              echo "❌ Performance benchmark failed"
              exit 1
            }
            echo "✅ Performance benchmark completed"
            cd ..
          else
            echo "ℹ️  No performance benchmark found, skipping..."
          fi

      - name: Stop Solana test validator
        run: |
          echo "🛑 Stopping Solana test validator..."
          pkill -f solana-test-validator || echo "ℹ️  No validator process found to stop"
          echo "✅ Validator cleanup completed"
