name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4



      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update dependencies
        run: |
          echo "📦 Updating project dependencies..."
          set -e
          
          echo "🔧 Updating root dependencies..."
          bun update || {
            echo "❌ Failed to update root dependencies"
            exit 1
          }
          echo "✅ Root dependencies updated successfully"
          
          echo "🔧 Updating SDK dependencies..."
          cd sdk
          bun update || {
            echo "❌ Failed to update SDK dependencies"
            exit 1
          }
          echo "✅ SDK dependencies updated successfully"
          
          echo "🔧 Updating CLI dependencies..."
          cd ../cli
          bun update || {
            echo "❌ Failed to update CLI dependencies"
            exit 1
          }
          echo "✅ CLI dependencies updated successfully"
          
          echo "🔧 Updating frontend dependencies..."
          cd ../frontend
          bun update || {
            echo "❌ Failed to update frontend dependencies"
            exit 1
          }
          echo "✅ Frontend dependencies updated successfully"
          echo "🎉 All dependencies updated successfully"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: 'Automated dependency updates'
          branch: dependency-updates